suppressMessages(library("rmarkdown"))
suppressMessages(library("markdown"))
suppressMessages(library("shiny"))
suppressMessages(library("devtools"))
suppressMessages(library("learnr"))
run("Quiz1.Rmd")
